### ISSUE TITLE
Some questions about run ”zs_base.sh“

### ISSUE THREAD

**Issue by wenyisir** [OpenMatch/Augmentation-Adapted-Retriever#3]
When I run the script run zs_base.sh, the output shows a FileNotFoundError: Unable to find 'XXX/Augmentation-Adapted-Retriever/scripts/LM/data/mmlu_msmarco_ra_ance_aar/cache/validation.jsonl'. Do I need to download any additional data?

**Comment by yuzc19** [comment]
Yes. You can follow the instructions [here](https://github.com/OpenMatch/Augmentation-Adapted-Retriever#2-dataset) to download our preprocessed dataset. Just remember to set your WORKING_DIR correctly.
