### ISSUE TITLE
Question about the missing data kilt_wikipedia.csv in the project.

### ISSUE THREAD

**Issue by EachSheep** [OpenMatch/Augmentation-Adapted-Retriever#4]
Hello, it seems that the corpus data `kilt_wikipedia` is missing in the data you provided at the link [preprocessed data](https://drive.google.com/file/d/1uYCGYXkYF3eMDbHTR2gSv1nmS_2bP-ZE/view). However, you are referencing this data in `post_pipeline.sh` and I didn't see the method for creating this data in the document. Could you please provide this missing data?

**Comment by yuzc19** [comment]
Hi! Thanks for pointing it out. Due to the large file size, it is not efficient to upload it to the cloud, but I have put the processing script in https://github.com/OpenMatch/Augmentation-Adapted-Retriever/blob/main/tools/process_kilt_wikipedia.py
